### ISSUE TITLE
Can I add more pics onto the page?

### ISSUE THREAD

**Issue by Guohao91** [rajaprerak/rajaprerak.github.io#10]
Hi, @rajaprerak 
I love your project and this layout design, so I would like to use this project to put in my own portfolio.
Before my act, I just wonder is that possible to add one or more pics on the pop-up panel after clicking any project instance?
like in here:
![1](https://user-images.githubusercontent.com/54188732/168409275-ca0db47a-d7cd-4f76-af1e-0766d74a5f40.png)

Looking forward your reply and thanks in advance~

**Comment by ThomasCarstens** [comment]
Hi, same query here, did you manage to put an image/ row of pictures?
